# Generated by Django 5.0 on 2024-06-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='tweets',
            field=models.JSONField(default=list, null=True),
        ),
    ]
